import {Audio, Sequence, staticFile} from 'remotion';
import {KanatanIntro} from './KanatanIntro';

// Narration lines generated by make-narration.sh (say -v Kyoko).
// Placement is tuned to the measured durations so each line lands on
// its scene: L1=clip1, L2-L3=clip2, L4-L5=clip3, L6=clip4.
const LINES: {file: string; from: number; rate?: number}[] = [
  {file: 'audio/line1.wav', from: 15},
  {file: 'audio/line2.wav', from: 250},
  {file: 'audio/line3.wav', from: 412},
  {file: 'audio/line4.wav', from: 548},
  {file: 'audio/line5.wav', from: 642, rate: 1.05},
  {file: 'audio/line6.wav', from: 738, rate: 1.1},
];

export const KanatanIntroNarrated: React.FC = () => {
  return (
    <>
      <KanatanIntro />
      {LINES.map((line) => (
        <Sequence key={line.file} from={line.from}>
          <Audio src={staticFile(line.file)} playbackRate={line.rate ?? 1} />
        </Sequence>
      ))}
    </>
  );
};
